# Generated by Django 4.0.6 on 2023-01-30 23:53

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default=None, upload_to=account.models.upload_location),
            preserve_default=False,
        ),
    ]
