# Generated by Django 4.0.6 on 2023-01-27 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_question_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
