# Generated by Django 4.0.6 on 2023-01-27 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_alter_question_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answercomment',
            name='answer',
        ),
        migrations.AddField(
            model_name='answer',
            name='comment',
            field=models.ManyToManyField(to='question.answercomment'),
        ),
    ]
