# Generated by Django 4.0.6 on 2023-01-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_remove_answercomment_answer_answer_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='answercomment',
            name='comment_answer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
