# Generated by Django 4.0.6 on 2023-01-30 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_answercomment_comment_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answercomment',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='question.answer'),
        ),
    ]
