# Generated by Django 4.0.6 on 2023-01-30 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_alter_answercomment_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='comment',
        ),
        migrations.AddField(
            model_name='answercomment',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_answer', to='question.answer'),
        ),
        migrations.AlterField(
            model_name='answercomment',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='question.question'),
        ),
    ]
