# Generated by Django 4.0.6 on 2023-01-30 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_remove_answer_comment_answercomment_answer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answercomment',
            name='comment_answer',
        ),
    ]
